# Generated by Django 6.0.4 on 2026-04-19 01:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], max_length=4)),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Confidence score 0-100%.', max_digits=5)),
                ('target_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('timeframe', models.CharField(choices=[('intraday', 'Intraday'), ('short_term', 'Short Term (1-7 days)'), ('medium_term', 'Medium Term (1-3 months)'), ('long_term', 'Long Term (3+ months)')], default='short_term', max_length=20)),
                ('reasoning', models.TextField(help_text='AI rationale for the suggestion.')),
                ('signals', models.JSONField(blank=True, default=dict, help_text='Technical indicators: RSI, MACD, moving averages, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.instrument')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_suggestions', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='Null = global suggestion for all premium users.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('acted_on', models.BooleanField(default=False, help_text='Did the user place a trade based on this?')),
                ('comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_bot.tradesuggestion')),
            ],
            options={
                'db_table': 'suggestion_feedback',
                'unique_together': {('suggestion', 'user')},
            },
        ),
    ]
