# Generated by Django 6.0.4 on 2026-04-19 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('symbol', models.CharField(help_text='e.g. BTC/USDT', max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('tick_size', models.DecimalField(decimal_places=8, default=0.01, max_digits=18)),
                ('maker_fee_pct', models.DecimalField(decimal_places=4, default=0.1, max_digits=5)),
                ('taker_fee_pct', models.DecimalField(decimal_places=4, default=0.1, max_digits=5)),
                ('base', models.ForeignKey(help_text='Base asset (e.g. BTC)', on_delete=django.db.models.deletion.CASCADE, related_name='base_pairs', to='market.instrument')),
                ('quote', models.ForeignKey(help_text='Quote asset (e.g. USDT)', on_delete=django.db.models.deletion.CASCADE, related_name='quote_pairs', to='market.instrument')),
            ],
            options={
                'db_table': 'crypto_pairs',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='OrderBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('bid', 'Bid'), ('ask', 'Ask')], max_length=3)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_book', to='crypto.cryptopair')),
            ],
            options={
                'db_table': 'order_book_entries',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='SwapOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('from_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('to_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=8, help_text='Exchange rate at execution', max_digits=18)),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='crypto.cryptopair')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_orders', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'swap_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
