# Generated by Django 6.0.4 on 2026-04-18 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop_loss', 'Stop Loss'), ('stop_loss_limit', 'Stop Loss Limit')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price', models.DecimalField(blank=True, decimal_places=8, help_text='Limit price (null for market orders)', max_digits=18, null=True)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=8, help_text='Stop-loss trigger price', max_digits=18, null=True)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('avg_fill_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('total_value', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('validity', models.CharField(choices=[('day', 'Day'), ('gtc', 'Good Till Cancelled'), ('ioc', 'Immediate or Cancel')], default='day', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.instrument')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('fee', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='orders.order')),
            ],
            options={
                'db_table': 'order_fills',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_user_id_17dbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['instrument', 'status'], name='orders_instrum_5f6304_idx'),
        ),
    ]
