# Generated by Django 6.0.4 on 2026-04-18 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('avg_buy_price', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('total_invested', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='market.instrument')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'holdings',
                'unique_together': {('user', 'instrument')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_snapshots',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
