# Generated by Django 6.0.4 on 2026-04-18 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto')], max_length=10)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'instruments',
                'ordering': ['symbol'],
                'unique_together': {('symbol', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltp', models.DecimalField(decimal_places=8, help_text='Last traded price', max_digits=18)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('high', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('low', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('close', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('prev_close', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('change', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('change_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='market.instrument')),
            ],
            options={
                'db_table': 'price_snapshots',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='My Watchlist', max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchlists',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.instrument')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market.watchlist')),
            ],
            options={
                'db_table': 'watchlist_items',
                'ordering': ['sort_order'],
                'unique_together': {('watchlist', 'instrument')},
            },
        ),
    ]
